version: '3.8'

services:
  mongo:
    image: mongo:5.0.7
    ports:
      - "27017:27017"
  flight-log-backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATA_MONGODB_URI=mongodb://mongo:27017/my_db
    depends_on:
      - mongo